<?php
if( function_exists('acf_add_local_field_group') ):

// Options Theme Setings - ACF Group
acf_add_local_field_group(array(
	'key' => 'group_5tk5c1be993d3445',
	'title' => __('General settings', 'tkm-functionality'),
	'fields' => array(
		array(
			'key' => 'field_5tk5c46csw2d',
			'label' => __('Style & Layout', 'tkm-functionality'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5tk5c96a32d8b39e',
			'label' => __('Site layout', 'tkm-functionality'),
			'name' => 'site_wrap_style',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'full_width' => __('Full width', 'tkm-functionality'),
				'boxed_site' => __('Box site', 'tkm-functionality'),
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5tk5c96a3648b39f',
			'label' => __('Background color', 'tkm-functionality'),
			'name' => 'site_bg_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5tk5c96a3918b3a0',
			'label' => __('Inner background color', 'tkm-functionality'),
			'name' => 'site_inner_bg_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),		
		array(
			'key' => 'field_5tk5c46c6c60855d',
			'label' => __('General info', 'tkm-functionality'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),		
		array(
			'key' => 'field_5tk5c46c6dc0855e',
			'label' => __('Main phone', 'tkm-functionality'),
			'name' => 'header_phone',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c4cbde89dc5e',
			'label' => __('Main contact - Phone text', 'tkm-functionality'),
			'name' => 'site_phone_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c4cbeba9dc5f',
			'label' => __('Phone for Whatsapp', 'tkm-functionality'),
			'name' => 'site_whatsapp_num',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c4cbed09dc60',
			'label' => __('Main contact - Whatsapp text', 'tkm-functionality'),
			'name' => 'site_whatsapp_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c4cbee69dc61',
			'label' => __('Main email', 'tkm-functionality'),
			'name' => 'site_main_email',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c4cbf009dc62',
			'label' => __('Main contact - Email text', 'tkm-functionality'),
			'name' => 'site_main_email_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c4cbf139dc63',
			'label' => __('Mobile phone', 'tkm-functionality'),
			'name' => 'site_main_cellphone',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c4cbf279dc64',
			'label' => __('Main contact - Mobile text', 'tkm-functionality'),
			'name' => 'site_main_cellphone_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c4cbf3a9dc65',
			'label' => __('Messanger', 'tkm-functionality'),
			'name' => 'site_messanger',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c4cbf4c9dc66',
			'label' => __('Main contact - Messanger text', 'tkm-functionality'),
			'name' => 'site_messanger_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5ca2510c0fa77',
			'label' => __('Facebook', 'tkm-functionality'),
			'name' => 'site_facebook',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5ca251280fa78',
			'label' => __('Main contact - Facebook text', 'tkm-functionality'),
			'name' => 'site_facebook_text',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5ca22aff8e4fb',
			'label' => __('Main share - Twitter text', 'tkm-functionality'),
			'name' => 'site_twitter_share',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5ca22b598e4fd',
			'label' => __('Main share - Facebook text', 'tkm-functionality'),
			'name' => 'site_facebook_share',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5ca22b778e501',
			'label' => __('Main share - Whatsapp text', 'tkm-functionality'),
			'name' => 'site_whatsapp_share',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5ca22b8a8e502',
			'label' => __('Main share - email text', 'tkm-functionality'),
			'name' => 'site_email_share',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c46c6ef0855f',
			'label' => __('Social links', 'tkm-functionality'),
			'name' => 'social_links',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5tk5c46c70408560',
					'label' => __('Icon', 'tkm-functionality'),
					'name' => 'social_links_icon',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => '',
					'custom_icon_set' => '',
					'default_label' => '',
					'default_value' => '',
					'save_format' => 'element',
					'allow_null' => 0,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'key' => 'field_5tk5c46c71708561',
					'label' => __('Link', 'tkm-functionality'),
					'name' => 'social_links_link',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5tk5c1be9a7ed7ae',
			'label' => __('Header', 'tkm-functionality'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'left',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5tk5c1hheb5',
			'label' => __('Logo width', 'tkm-functionality'),
			'name' => 'header_logo_width',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'default_value' => '200',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => '',
			'max' => '',
			'step' => '',
		),		
		array(
			'key' => 'field_5tk5c1be9b3ed7af',
			'label' => __('Header style', 'tkm-functionality'),
			'name' => 'header_style',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'full_row_box normal_menu' => __('Logo on side of nav', 'tkm-functionality'),
				'split_row_box normal_menu' => __('Logo above nav', 'tkm-functionality'),
				'header_logo_center_nav normal_menu' => __('Logo center nav', 'tkm-functionality'),
				'header_logo_center_no_nav' => __('Logo center NO nav', 'tkm-functionality'),
				'header_logo_r_no_nav' => __('Logo side NO nav', 'tkm-functionality'),
				'full_site_hamburger' => __('Logo with Hamburger nav', 'tkm-functionality'),
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5tk5c96a3e7d88f5',
			'label' => __('Header background color', 'tkm-functionality'),
			'name' => 'header_bg_color',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'header_dark' => __('Dark', 'tkm-functionality'),
				'header_light' => __('Light', 'tkm-functionality'),
				'header_trans' => __('Transparent', 'tkm-functionality'),
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5tk5c6dhngd7b',
			'label' => __('Logo position (desktop)', 'tkm-functionality'),
			'name' => 'header_logo_side_position',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c1be9b3ed7af',
						'operator' => '==',
						'value' => 'full_row_box normal_menu',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'logo_side_start' => __('Logo strat', 'tkm-functionality'),
				'logo_side_end' => __('Logo end', 'tkm-functionality'),
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),		
		array(
			'key' => 'field_5tk5c629d581dd7b',
			'label' => __('Logo position (desktop)', 'tkm-functionality'),
			'name' => 'header_logo_side',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c1be9b3ed7af',
						'operator' => '==',
						'value' => 'split_row_box normal_menu',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c1be9b3ed7af',
						'operator' => '==',
						'value' => 'header_logo_r_no_nav',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'logo_side_right' => __('Logo right', 'tkm-functionality'),
				'logo_side_center' => __('Logo center', 'tkm-functionality'),
				'logo_side_left' => __('Logo left', 'tkm-functionality'),
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5tk5c627wrgdbb',
			'label' => __('Menu item layout', 'tkm-functionality'),
			'name' => 'menu_item_layout',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5tk5c1be9b3ed7af',
						'operator' => '==',
						'value' => 'full_row_box normal_menu',
					),
				),
				array(
					array(
						'field' => 'field_5tk5c1be9b3ed7af',
						'operator' => '==',
						'value' => 'split_row_box normal_menu',
					),
				),
			),
			'wrapper' => array(
				'width' => '25',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'spread_nav' => __('Spread items evenly', 'tkm-functionality'),
				'align_start_nav' => __('Align item start', 'tkm-functionality'),
				'align_end_nav' => __('Align item end', 'tkm-functionality'),
				'align_center_nav' => __('Align item center', 'tkm-functionality'),
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),
		array(
			'key' => 'field_5tk5c728aec08fc8',
			'label' => __('Default top slider image', 'tkm-functionality'),
			'name' => 'default_main_masthead_bg',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'menu-50',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5dskjsd3b0',
			'label' => __('Desktop Sticky header - fixed', 'tkm-functionality'),
			'name' => 'desktop_sticky_fixed',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5dskjkhdsad3e40',
			'label' => __('Mobile Sticky header - fixed', 'tkm-functionality'),
			'name' => 'mobile_sticky_fixed',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '30',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),						
		array(
			'key' => 'field_5tk5c1cafd6fd445',
			'label' => __('Default slider title size', 'tkm-functionality'),
			'name' => 'home_masthead_content_title',
			'type' => 'number',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '40',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => 'px',
			'min' => '',
			'max' => '',
			'step' => '',
		),
		array(
			'key' => 'field_5ds36b457cf3ed',
			'label' => __('Top panel', 'tkm-functionality'),
			'name' => 'header_top_panel_option',
			'type' => 'group',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '65',
				'class' => '',
				'id' => '',
			),
			'layout' => 'block',
			'sub_fields' => array(
			),
		),
		array(
			'key' => 'field_5tk5c62dd22bb',
			'label' => __('Top panel position', 'tkm-functionality'),
			'name' => 'top_panel_position',
			'type' => 'radio',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjkh60beb0',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '35',
				'class' => '',
				'id' => '',
			),
			'choices' => array(
				'top_panel_top' => __('Position above header', 'tkm-functionality'),
				'top_panel_side' => __('Position beside header', 'tkm-functionality'),
			),
			'allow_null' => 0,
			'other_choice' => 0,
			'default_value' => '',
			'layout' => 'vertical',
			'return_format' => 'value',
			'save_other_choice' => 0,
		),				
		array(
			'key' => 'field_5dskjkh60beb0',
			'label' => __('Show top panel', 'tkm-functionality'),
			'name' => 'header_top_panel_show',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5tk5cjshdj2fd',
			'label' => __('Top panel bg color', 'tkm-functionality'),
			'name' => 'header_top_panel_bg_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjkh60beb0',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),
		array(
			'key' => 'field_5tk0jwgt2b3fd',
			'label' => __('Top panel text color', 'tkm-functionality'),
			'name' => 'header_top_panel_font_color',
			'type' => 'color_picker',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjkh60beb0',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
		),				
		array(
			'key' => 'field_5dskjfvep00',
			'label' => __('Show phone in top panel', 'tkm-functionality'),
			'name' => 'header_top_panel_phone_show',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjkh60beb0',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),	
		array(
			'key' => 'field_5dskjfggsp00',
			'label' => __('Show nav in top panel', 'tkm-functionality'),
			'name' => 'header_top_panel_nav_show',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjkh60beb0',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),													
		array(
			'key' => 'field_5tk5c362960b10a0',
			'label' => __('Top panel - right text', 'tkm-functionality'),
			'name' => 'header_top_panel_right',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjkh60beb0',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),		
		array(
			'key' => 'field_5tk5cce8c275259b',
			'label' => __('Top panel - left', 'tkm-functionality'),
			'name' => 'header_top_nav_left',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjkh60beb0',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5tk5cce8c4c5259c',
					'label' => __('Icon', 'tkm-functionality'),
					'name' => 'header_top_nav_left_icon',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'fas',
						1 => 'far',
						2 => 'fal',
						3 => 'fab',
					),
					'custom_icon_set' => '',
					'default_label' => '',
					'default_value' => '',
					'save_format' => 'element',
					'allow_null' => 1,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'key' => 'field_5tk5cce8c5d5259d',
					'label' => __('Text', 'tkm-functionality'),
					'name' => 'header_top_nav_left_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5tk5cce8c6c5259e',
					'label' => __('Link', 'tkm-functionality'),
					'name' => 'header_top_nav_left_link',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5tk5cce994ce0e24',
			'label' => __('Top panel - left nav on mobile only', 'tkm-functionality'),
			'name' => 'header_mobile_left',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjkh60beb0',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5tk5cce994ce0e25',
					'label' => __('Icon', 'tkm-functionality'),
					'name' => 'header_mobile_left_icon',
					'type' => 'font-awesome',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'icon_sets' => array(
						0 => 'fas',
						1 => 'far',
						2 => 'fal',
						3 => 'fab',
					),
					'custom_icon_set' => '',
					'default_label' => '',
					'default_value' => '',
					'save_format' => 'element',
					'allow_null' => 1,
					'show_preview' => 1,
					'enqueue_fa' => 0,
					'fa_live_preview' => '',
					'choices' => array(
					),
				),
				array(
					'key' => 'field_5tk5cce994ce0e26',
					'label' => __('Text', 'tkm-functionality'),
					'name' => 'header_mobile_left_text',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5tk5cce994ce0e27',
					'label' => __('Link', 'tkm-functionality'),
					'name' => 'header_mobile_left_link',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
			),
		),
		array(
			'key' => 'field_5tk5c46c630354f3',
			'label' => __('Footer', 'tkm-functionality'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5cf623bbdd3',
			'label' => __('Footer Content Elements', 'tkm-functionality'),
			'name' => 'footer_flex_content',
			'type' => 'flexible_content',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'layouts' => array(
				'layout_5cf623csdde12' => array(
					'key' => 'layout_5cf623csdde12',
					'name' => 'footer_full_contnet',
					'label' => __('Full content', 'tkm-functionality'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d1073bdsd4d',
							'label' => __('Block Width', 'tkm-functionality'),
							'name' => 'footer_full_contnet_block_width',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'col-md-12' => __('full width', 'tkm-functionality'),
								'col-sm-6 col-md-1' => '8.33%',
								'col-sm-6 col-md-2' => '16.67%',
								'col-sm-6 col-md-3' => '25%',
								'col-sm-6 col-md-4' => '33.33%',
								'col-sm-6 col-md-5' => '42.85%',
								'col-sm-6 col-md-6' => '50%',
								'col-sm-6 col-md-7' => '57.15%',
								'col-sm-6 col-md-8' => '66.67%',
								'col-sm-6 col-md-9' => '75%',
								'col-sm-6 col-md-10' => '83.33%',
								'col-sm-6 col-md-11' => '91.67%',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5tk5cd2dy67f1',
							'label' => __('Mobile layout', 'tkm-functionality'),
							'name' => 'footer_full_contnet_mobile',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'col-xs-12' => __('100%', 'tkm-functionality'),
								'col-xs-6' => __('50%', 'tkm-functionality'),
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5tk5c09jd5e5',
							'label' => __('Hide On Mobile', 'tkm-functionality'),
							'name' => 'footer_full_contnet_hide_mobile',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5tk5c8dfd12cd',
							'label' => __('Title', 'tkm-functionality'),
							'name' => 'footer_full_contnet_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5tk5cc54wewe3e238',
							'label' => __('Title - font size', 'tkm-functionality'),
							'name' => 'footer_full_contnet_title_size',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => 'px',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'field_5tk5c992we4ec',
							'label' => __('Title color', 'tkm-functionality'),
							'name' => 'footer_full_contnet_title_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
						array(
							'key' => 'field_5tk5dhj769f261',
							'label' => __('Content', 'tkm-functionality'),
							'name' => 'footer_full_contnet_text',
							'type' => 'wysiwyg',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'tabs' => 'all',
							'toolbar' => 'full',
							'media_upload' => 1,
							'delay' => 0,
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5cf623c2s332' => array(
					'key' => 'layout_5cf623c2s332',
					'name' => 'footer_search_bar',
					'label' => __('Search bar', 'tkm-functionality'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d1073dd34d',
							'label' => __('Block Width', 'tkm-functionality'),
							'name' => 'footer_search_bar_block_width',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'col-md-12' => __('full width', 'tkm-functionality'),
								'col-sm-6 col-md-1' => '8.33%',
								'col-sm-6 col-md-2' => '16.67%',
								'col-sm-6 col-md-3' => '25%',
								'col-sm-6 col-md-4' => '33.33%',
								'col-sm-6 col-md-5' => '42.85%',
								'col-sm-6 col-md-6' => '50%',
								'col-sm-6 col-md-7' => '57.15%',
								'col-sm-6 col-md-8' => '66.67%',
								'col-sm-6 col-md-9' => '75%',
								'col-sm-6 col-md-10' => '83.33%',
								'col-sm-6 col-md-11' => '91.67%',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5tk5cdss27f1',
							'label' => __('Mobile layout', 'tkm-functionality'),
							'name' => 'footer_search_bar_mobile',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'col-xs-12' => __('100%', 'tkm-functionality'),
								'col-xs-6' => __('50%', 'tkm-functionality'),
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5tksss2jd5e5',
							'label' => __('Hide On Mobile', 'tkm-functionality'),
							'name' => 'footer_search_bar_hide_mobile',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5tk5dhsssd161',
							'label' => __('Show search bar', 'tkm-functionality'),
							'name' => 'footer_search_bar_show',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
					),
					'min' => '',
					'max' => '',
				),				
				'layout_5d1072sw39' => array(
					'key' => 'layout_5d1072sw39',
					'name' => 'footer_nav',
					'label' => __('Footer Nav', 'tkm-functionality'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d107scv4d',
							'label' => __('Block Width', 'tkm-functionality'),
							'name' => 'footer_nav_block_width',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'col-md-12' => __('full width', 'tkm-functionality'),
								'col-sm-6 col-md-1' => '8.33%',
								'col-sm-6 col-md-2' => '16.67%',
								'col-sm-6 col-md-3' => '25%',
								'col-sm-6 col-md-4' => '33.33%',
								'col-sm-6 col-md-5' => '42.85%',
								'col-sm-6 col-md-6' => '50%',
								'col-sm-6 col-md-7' => '57.15%',
								'col-sm-6 col-md-8' => '66.67%',
								'col-sm-6 col-md-9' => '75%',
								'col-sm-6 col-md-10' => '83.33%',
								'col-sm-6 col-md-11' => '91.67%',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5tk5cd22sdvv1',
							'label' => __('Mobile layout', 'tkm-functionality'),
							'name' => 'footer_nav_mobile',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'col-xs-12' => __('100%', 'tkm-functionality'),
								'col-xs-6' => __('50%', 'tkm-functionality'),
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5tk5c0scf5',
							'label' => __('Hide On Mobile', 'tkm-functionality'),
							'name' => 'footer_nav_hide_mobile',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5tk52ddfcd',
							'label' => __('Title', 'tkm-functionality'),
							'name' => 'footer_nav_title',
							'type' => 'text',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => '',
							'maxlength' => '',
						),
						array(
							'key' => 'field_5tk5sdc4238',
							'label' => __('Title - font size', 'tkm-functionality'),
							'name' => 'footer_nav_title_size',
							'type' => 'number',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
							'placeholder' => '',
							'prepend' => '',
							'append' => 'px',
							'min' => '',
							'max' => '',
							'step' => '',
						),
						array(
							'key' => 'field_5tk52aaac',
							'label' => __('Title color', 'tkm-functionality'),
							'name' => 'footer_nav_title_color',
							'type' => 'color_picker',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'default_value' => '',
						),
						array(
							'key' => 'field_5d10swe3d',
							'label' => __('Choose nav', 'tkm-functionality'),
							'name' => 'footer_nav_choose',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'footer-nav-1' =>  __('Footer nav 1', 'tkm-functionality'),
								'footer-nav-2' =>  __('Footer nav 2', 'tkm-functionality'),
								'footer-nav-3' =>  __('Footer nav 3', 'tkm-functionality'),
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
					),
					'min' => '',
					'max' => '',
				),
				'layout_5cf62sw2d333' => array(
					'key' => 'layout_5cf62sw2d333',
					'name' => 'footer_social_links',
					'label' => __('Social links', 'tkm-functionality'),
					'display' => 'block',
					'sub_fields' => array(
						array(
							'key' => 'field_5d1073dss22qqwd',
							'label' => __('Block Width', 'tkm-functionality'),
							'name' => 'footer_social_links_block_width',
							'type' => 'select',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'col-md-12' => __('full width', 'tkm-functionality'),
								'col-sm-6 col-md-1' => '8.33%',
								'col-sm-6 col-md-2' => '16.67%',
								'col-sm-6 col-md-3' => '25%',
								'col-sm-6 col-md-4' => '33.33%',
								'col-sm-6 col-md-5' => '42.85%',
								'col-sm-6 col-md-6' => '50%',
								'col-sm-6 col-md-7' => '57.15%',
								'col-sm-6 col-md-8' => '66.67%',
								'col-sm-6 col-md-9' => '75%',
								'col-sm-6 col-md-10' => '83.33%',
								'col-sm-6 col-md-11' => '91.67%',
							),
							'default_value' => array(
							),
							'allow_null' => 0,
							'multiple' => 0,
							'ui' => 1,
							'return_format' => 'value',
							'ajax' => 0,
							'placeholder' => '',
						),
						array(
							'key' => 'field_5tk5cs22ew2e1',
							'label' => __('Mobile layout', 'tkm-functionality'),
							'name' => 'footer_social_links_mobile',
							'type' => 'radio',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'choices' => array(
								'col-xs-12' => __('100%', 'tkm-functionality'),
								'col-xs-6' => __('50%', 'tkm-functionality'),
							),
							'allow_null' => 0,
							'other_choice' => 0,
							'default_value' => '',
							'layout' => 'horizontal',
							'return_format' => 'value',
							'save_other_choice' => 0,
						),
						array(
							'key' => 'field_5tksss2esfe5',
							'label' => __('Hide On Mobile', 'tkm-functionality'),
							'name' => 'footer_social_links_hide_mobile',
							'type' => 'true_false',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '33',
								'class' => '',
								'id' => '',
							),
							'message' => '',
							'default_value' => 0,
							'ui' => 1,
							'ui_on_text' => '',
							'ui_off_text' => '',
						),
						array(
							'key' => 'field_5tk5c8esds38a4',
							'label' => __('Footer social links', 'tkm-functionality'),
							'name' => 'footer_social_links_row',
							'type' => 'repeater',
							'instructions' => '',
							'required' => 0,
							'conditional_logic' => 0,
							'wrapper' => array(
								'width' => '',
								'class' => '',
								'id' => '',
							),
							'collapsed' => '',
							'min' => 0,
							'max' => 0,
							'layout' => 'table',
							'button_label' => '',
							'sub_fields' => array(
								array(
									'key' => 'field_5tk5cs22638a5',
									'label' => __('Icon', 'tkm-functionality'),
									'name' => 'footer_social_links_icon',
									'type' => 'font-awesome',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'icon_sets' => array(
										0 => 'fas',
										1 => 'far',
										2 => 'fal',
										3 => 'fab',
									),
									'custom_icon_set' => '',
									'default_label' => '',
									'default_value' => '',
									'save_format' => 'element',
									'allow_null' => 0,
									'show_preview' => 1,
									'enqueue_fa' => 0,
									'fa_live_preview' => '',
									'choices' => array(
									),
								),
								array(
									'key' => 'field_5tk5c8sdwd3638a6',
									'label' => __('Link', 'tkm-functionality'),
									'name' => 'footer_social_links_link',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
								array(
									'key' => 'field_5tk5cdw33338a7',
									'label' => __('Text', 'tkm-functionality'),
									'name' => 'footer_social_links_text',
									'type' => 'text',
									'instructions' => '',
									'required' => 0,
									'conditional_logic' => 0,
									'wrapper' => array(
										'width' => '',
										'class' => '',
										'id' => '',
									),
									'default_value' => '',
									'placeholder' => '',
									'prepend' => '',
									'append' => '',
									'maxlength' => '',
								),
							),
						),		
					),
					'min' => '',
					'max' => '',
				),				
			),
			'button_label' => __('Add new block', 'tkm-functionality'),
			'min' => '',
			'max' => '',
		),
		array(
			'key' => 'field_5dskjjhrhy64',
			'label' => __('Show mobile fixed bar', 'tkm-functionality'),
			'name' => 'footer_bar_show',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),													
		array(
			'key' => 'field_5dskjjhrws33',
			'label' => __('Show search button', 'tkm-functionality'),
			'name' => 'footer_search_show',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjjhrhy64',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),													
		array(
			'key' => 'field_5dsksn6ggg33',
			'label' => __('Show Page link button', 'tkm-functionality'),
			'name' => 'footer_link_show',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjjhrhy64',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),
		array(
			'key' => 'field_5dsksn6wd3dd3',
			'label' => __('Show Free link button', 'tkm-functionality'),
			'name' => 'footer_free_link_show',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjjhrhy64',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),																												
		array(
			'key' => 'field_5dskjj2sd33',
			'label' => __('Show form popup button', 'tkm-functionality'),
			'name' => 'footer_popup_show',
			'type' => 'true_false',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjjhrhy64',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '20',
				'class' => '',
				'id' => '',
			),
			'message' => '',
			'default_value' => 0,
			'ui' => 1,
			'ui_on_text' => '',
			'ui_off_text' => '',
		),													
		array(
			'key' => 'field_5dsksal09g33',
			'label' => __('Link button Icon', 'tkm-functionality'),
			'name' => 'footer_fixed_link_icon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dsksn6ggg33',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fal',
				3 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '',
			'default_value' => '',
			'save_format' => 'element',
			'allow_null' => 1,
			'show_preview' => 1,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5tk5as0sj75',
			'label' => __('Link btn text', 'tkm-functionality'),
			'name' => 'footer_fixed_link_btn',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dsksn6ggg33',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5as0kj465',
			'label' => __('Link to', 'tkm-functionality'),
			'name' => 'footer_fixed_link_page',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dsksn6ggg33',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5dsksal09ddg33',
			'label' => __('Free link button Icon', 'tkm-functionality'),
			'name' => 'footer_fixed_free_link_icon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dsksn6wd3dd3',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fal',
				3 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '',
			'default_value' => '',
			'save_format' => 'element',
			'allow_null' => 1,
			'show_preview' => 1,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5tk5as0dedd333',
			'label' => __('Free link button text', 'tkm-functionality'),
			'name' => 'footer_fixed_free_link_btn',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dsksn6wd3dd3',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5as0kjdds65',
			'label' => __('Free link button to', 'tkm-functionality'),
			'name' => 'footer_fixed_free_link_page',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dsksn6wd3dd3',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5dsksasdeww333',
			'label' => __('Popup form Icon', 'tkm-functionality'),
			'name' => 'footer_fixed_form_icon',
			'type' => 'font-awesome',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjj2sd33',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'icon_sets' => array(
				0 => 'fas',
				1 => 'far',
				2 => 'fal',
				3 => 'fab',
			),
			'custom_icon_set' => '',
			'default_label' => '',
			'default_value' => '',
			'save_format' => 'element',
			'allow_null' => 1,
			'show_preview' => 1,
			'enqueue_fa' => 0,
			'fa_live_preview' => '',
			'choices' => array(
			),
		),
		array(
			'key' => 'field_5tk5sde3dqq75',
			'label' => __('Popup form text', 'tkm-functionality'),
			'name' => 'footer_fixed_form_btn',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjj2sd33',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),		
		array(
			'key' => 'field_5tk5c2dd552a7',
			'label' => __('Choose Form', 'tkm-functionality'),
			'name' => 'footer_form_id',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjj2sd33',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'wpcf7_contact_form',
			),
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
		array(
			'key' => 'field_5tk5as2132a5',
			'label' => __('Title', 'tkm-functionality'),
			'name' => 'footer_form_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjj2sd33',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5cbs2qqa6',
			'label' => __('Subtitle', 'tkm-functionality'),
			'name' => 'footer_form_subtitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => array(
				array(
					array(
						'field' => 'field_5dskjj2sd33',
						'operator' => '==',
						'value' => '1',
					),
				),
			),
			'wrapper' => array(
				'width' => '33',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),		
		array(
			'key' => 'field_5tk5c48eefb0',
			'label' => __('Site popups and Forms', 'tkm-functionality'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5tk5cdss268f7',
			'label' => __('Page default form title', 'tkm-functionality'),
			'name' => 'default_flex_form_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c97ddds3',
			'label' => __('Page default form subtitle', 'tkm-functionality'),
			'name' => 'default_flex_form_subtitle',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5h376ha7',
			'label' => __('Default form popup', 'tkm-functionality'),
			'name' => 'default_form_popup',
			'type' => 'relationship',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'post_type' => array(
				0 => 'wpcf7_contact_form',
			),
			'taxonomy' => '',
			'filters' => array(
				0 => 'search',
				1 => 'post_type',
				2 => 'taxonomy',
			),
			'elements' => '',
			'min' => '',
			'max' => '',
			'return_format' => 'object',
		),
		array(
			'key' => 'field_5tk5c72dc33bf',
			'label' => __('Footer default form bg', 'tkm-functionality'),
			'name' => 'default_flex_form_bg',
			'type' => 'image',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'return_format' => 'id',
			'preview_size' => 'thumbnail',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),					
		array(
			'key' => 'field_5tk5c48c472b43b0',
			'label' => __('Site elements', 'tkm-functionality'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5tk5c96a478d88f7',
			'label' => __('Popup form title', 'tkm-functionality'),
			'name' => 'popup_contact_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c5699c40484f',
			'label' => __('Main category page link', 'tkm-functionality'),
			'name' => 'default_main_cat',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c48c485b43b1',
			'label' => __('Contact module phone', 'tkm-functionality'),
			'name' => 'default_phone_num',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c48c4a8b43b2',
			'label' => __('Contact module button text', 'tkm-functionality'),
			'name' => 'default_phone_btn',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c48c4c0b43b3',
			'label' => __('Contact module Whatsapp num', 'tkm-functionality'),
			'name' => 'default_whatsapp_num',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c48c4d7b43b4',
			'label' => __('Contact module Whatsapp text', 'tkm-functionality'),
			'name' => 'default_whatsapp_btn',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '50',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c50b487b403d',
			'label' => __('Default client slider', 'tkm-functionality'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5tk5c9opd7y0',
			'label' => __('Images', 'tkm-functionality'),
			'name' => 'client_slider_image',
			'type' => 'gallery',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'min' => '',
			'max' => '',
			'insert' => 'append',
			'library' => 'all',
			'min_width' => '',
			'min_height' => '',
			'min_size' => '',
			'max_width' => '',
			'max_height' => '',
			'max_size' => '',
			'mime_types' => '',
		),
		array(
			'key' => 'field_5tk5c519970ae3c1',
			'label' => __('Default testimonial slider', 'tkm-functionality'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5tk5c51999dae3c2',
			'label' => __('Title', 'tkm-functionality'),
			'name' => 'site_testimonials_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c5199b0ae3c3',
			'label' => __('Testimonials', 'tkm-functionality'),
			'name' => 'site_testimonials_list',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5tk5c519a0eae3c4',
					'label' => __('Name', 'tkm-functionality'),
					'name' => 'site_testimonial_name',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5tk5c519a3cae3c5',
					'label' => __('Image', 'tkm-functionality'),
					'name' => 'site_testimonial_img',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5tk5c519a52ae3c6',
					'label' => __('Testimonial', 'tkm-functionality'),
					'name' => 'site_testimonial_content',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 5,
					'new_lines' => 'br',
				),
			),
		),
		array(
			'key' => 'field_5tk5c7e9790228e5',
			'label' => __('404 page', 'tkm-functionality'),
			'name' => '',
			'type' => 'tab',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'placement' => 'top',
			'endpoint' => 0,
		),
		array(
			'key' => 'field_5tk5c7e979f228e6',
			'label' => __('Error brand points title', 'tkm-functionality'),
			'name' => 'error_brand_points_title',
			'type' => 'text',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'default_value' => '',
			'placeholder' => '',
			'prepend' => '',
			'append' => '',
			'maxlength' => '',
		),
		array(
			'key' => 'field_5tk5c7e97bd228e7',
			'label' => __('Error brand box', 'tkm-functionality'),
			'name' => 'error_brand_points_box',
			'type' => 'repeater',
			'instructions' => '',
			'required' => 0,
			'conditional_logic' => 0,
			'wrapper' => array(
				'width' => '',
				'class' => '',
				'id' => '',
			),
			'collapsed' => '',
			'min' => 0,
			'max' => 0,
			'layout' => 'table',
			'button_label' => '',
			'sub_fields' => array(
				array(
					'key' => 'field_5tk5c7e97e4228e8',
					'label' => __('Icon/Image', 'tkm-functionality'),
					'name' => 'error_brand_points_box_icon',
					'type' => 'image',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'return_format' => 'id',
					'preview_size' => 'thumbnail',
					'library' => 'all',
					'min_width' => '',
					'min_height' => '',
					'min_size' => '',
					'max_width' => '',
					'max_height' => '',
					'max_size' => '',
					'mime_types' => '',
				),
				array(
					'key' => 'field_5tk5c7e981f228e9',
					'label' => __('Title', 'tkm-functionality'),
					'name' => 'error_brand_points_box_title',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5tk5c7e982a228ea',
					'label' => __('Subtitle', 'tkm-functionality'),
					'name' => 'error_brand_points_box_subtitle',
					'type' => 'textarea',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'maxlength' => '',
					'rows' => 3,
					'new_lines' => '',
				),
				array(
					'key' => 'field_5tk5c7e9839228eb',
					'label' => __('Button', 'tkm-functionality'),
					'name' => 'error_brand_points_box_btn',
					'type' => 'text',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'default_value' => '',
					'placeholder' => '',
					'prepend' => '',
					'append' => '',
					'maxlength' => '',
				),
				array(
					'key' => 'field_5tk5c7e9842228ec',
					'label' => __('Link', 'tkm-functionality'),
					'name' => 'error_brand_points_box_link',
					'type' => 'page_link',
					'instructions' => '',
					'required' => 0,
					'conditional_logic' => 0,
					'wrapper' => array(
						'width' => '',
						'class' => '',
						'id' => '',
					),
					'post_type' => '',
					'taxonomy' => '',
					'allow_null' => 0,
					'allow_archives' => 1,
					'multiple' => 0,
				),
			),
		),
	),
	'location' => array(
		array(
			array(
				'param' => 'options_page',
				'operator' => '==',
				'value' => 'theme-general-settings',
			),
		),
	),
	'menu_order' => 0,
	'position' => 'normal',
	'style' => 'default',
	'label_placement' => 'top',
	'instruction_placement' => 'label',
	'hide_on_screen' => '',
	'active' => true,
	'description' => '',
	'modified' => 1557043585,
));

endif;

?>
